### ISSUE TITLE
[FEAT] - Add token and key registry getters.

### ISSUE THREAD

**Issue by MatteuSan** [MatteuSan/sentro#4]
**Suggestion Details**
Add a function that retrieves all tokens and keys from registries.

**Suggestion Context**
This will greatly benefit authoring utility classes based on given tokens/keys.

**Possible Implementation**
Here's my suggested public API in the context of being used in generating utility classes based on tokens.
```scss
@use 'node_modules/@matteusan/sentro' with (
  $prefix: 'hc',
  $context: 'theme'
);

:root {
  @include sentro.token-config(
    // $tokens go here...
  );
}

/// @access private
/// @type map
$_design-tokens: sentro.token-registry-get(); // returns a map of tokens with its corresponding values.

@each $token, $value in $_design-tokens {
  .#{$token}-#{$value} {
     property: $value;
  }
}
```
I do think having a `$targets` parameter is useful for only querying tokens with a specific prefix like `padding` or `color`.
```scss
$_design-tokens: sentro.token-registry-get(('padding', 'color')); 
```
